version: '3'
services:
  app:
    image: axelcb/tripter:0.0.4
    command: java -jar /app/tripter.jar
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=docker
    depends_on:
      - "postgres"
    
  postgres:
    image: "postgres"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=docker